name: PR Agent Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write   # مهم جداً لكتابة تعليقات على الـ PR

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run PR Agent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_AGENT_AUTO_REVIEW: "true"        # شغّل المراجعة تلقائياً
          PR_AGENT_REVIEW_COMMENT: "true"     # يكتب ملخّص في Conversation
          PR_AGENT_REVIEW_INLINE: "true"      # يكتب تعليقات سطر-بسطر في Files changed
          PR_AGENT_CODE_SUGGESTIONS: "true"   # يقترح باتشات (اختياري)




