name: PR Agent Auto Explanation

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  explain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run PR Agent for explanation
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_AGENT_AUTO_REVIEW: "true"
          PR_AGENT_REVIEW_COMMENT: "true"
          PR_AGENT_SUMMARY: "true"
          PR_AGENT_MODE: "explain" # ← هذا السطر المهم

